# The Six W's About R packages

Many R users struggle with R packages. The problem is largely because the useful information is scattered or burried in text written mainly for developers, the fairly experienced fellows who create R packages (e.g. the [R Packages](http://r-pkgs.had.co.nz/) book by Hadley Wickham, and [these slides](https://speakerdeck.com/jennybc/ubc-stat545-2015-writing-your-first-r-package) by Jenny Bryan). This document helps R users to understand and use R packages by briefly answering the [Six W's](https://en.wikipedia.org/wiki/Five_Ws) about R packages, targetting specifically an imaginary R user with no background.



# What Is An R Package?
* Quote definition from rpkgs or JB slides
* Image of devtools cheetsheet

An R package is a kind of _Inflatable Castle_: A castle that inflates. An _Inflatable Castle_ can be big and red, but it can't have a massive hole -- the hole won't let it inflate, so if your castle has a massive hole it is no longer an _Inflatable Castle_. (Sad, I know). Similarly, an R package is a very specific collection of files and folders. To meet the definition of "R package", the names and structure of those files and folders have to meet some expectations. If you doon't meet them, you have files and folders but not an R package.

## Source Versus Built
Can you have a deflated _Inflatable Castle_? Yes you can. The deflated _Inflatable Castle_ isn't good for jumping on, but it is good for other things, like cleaning it. Similarly, to clean or maintain an R package you need its "deflated" or source state. The source of a package has all you need to build it but you can't use it for its main purpose until you actually build it. This built, "inflated", state of an R package is what you use to have fun.

## The Useful Stuff In An R Package
(What is each of these items? Link to examples)
* Functions (computer programs)
* Data
* Index: 
* Descriptons
* Help files
* Dependencies

# Why Is An R Package Useful?
An R package is useful because it makes it easy to share and use the functions (computer programs) and/or the data that it contains, and the documents that explain how to use those functions (See What Is An R Package > The Useful Stuff In An R Package xxx_add_link). An R package makes all its components available from one place: The R console. Thus R packages help you to find what you need quickly. Thay way you can spend most of your time working on whatever you want to accomplish rather than on the mundane task of searching for auxiliary information scattered in your computer or online. Having everything you need structured as an R package is convenient.

# Who Creates And Uses An R Package?
Anyone can create an R package. Simply put, you create a package if you put it together. Generally that means that you would also fix any issues and update the package. For a formal definition of the different roles you can take in relation an R package see the help file of the function [`person()`](https://goo.gl/Mk9ccJ) (click th link or run this the R console: `?person`).

Also anyone can use an R package; or more precisely, everyone must use R packages. Why? Because almost everything you do in R uses code that lives in an R package.  That is true for even the simplest computations: For example, if you run in the R console `1 + 2` you are using the __base__ package. Confirm this by running in the R console `?Arithmetic` or `?`+`` (or click [here](https://goo.gl/uKKv6f)). That help file refers to the __base__ package in two places: at the very top it says "Arithmetic {__base__}"; and at the very bottom it says "[Package __base__ version ... Index]". The package __base__ -- and a few others -- come with R. With those default packages you can do a lot of things but often you may want to use other packages to extend the basic functionality of R.

# Where does an R package live?
An R package can live locally in your computer, or remotely in a number of websites such as [CRAN](https://cran.r-project.org/) [GitHub] and (https://github.com/). More specifically, an R package always lives inside a folder -- the root directory -- that contains all its components. 

Notice that we commonly use the word "repo" to refer to a folder in an onilne repository (with or without code). So if someones says "go to the repo of package X" they are directing you to the website where you can see the folder containing the package X.

# When Is An R Packages Created, Shared, Used, And Updated?

## When Are R Packages Created
You create an R package in your computer whenever you combine its fundamental components (which are surprisingly few). Simply, that is when you run `devtools::create("name-of-your-package")`, or when you click these menues in RStudio: File > New Project ... > New Directory > R Package.

## When Are R Packages Shared
You share an R package whenever you allow at least one more person to access it. For example:
  * When you give your colleague the dropbox link to download the folder containing the source code of your R package.
  * When you authorize your colleague to access the private GitHub-repo of your R package.
  * When you publish your R package on CRAN so your colleague can install the package with `install.packages()`; or when you host your R package in a public repo (i.e. directory or folder) on GitHub so your colleague can install the package with `devtools::install_github()`.
  * When you email your colleague the a [built binary](TODO insert link to rpkgs) version of your R package.

Notice that you can share an R package in any state of development. How can your colleague know if the code is still in draft stage or it is polished and safe to use? The stable snapshots (versions) of your code you can flag with a label _Release_. When you publish on CRAN a snapshot of your code, that snapshot is associated to a version number that represents that particular release. But CRAN is not the only platform that allows that. You can also release snapshots of your code even if it lives only on more informal repositories. For example, here are the instructions for [Creating Releases](https://help.github.com/articles/creating-releases/) on GitHub.

## When Are R Packages Used

When you start a new R session you may need to set things up by installing and loding (opening) some packages. The steps you follow to use an R package or any other software are alike. If you want to use Chrome your neet to first install Chrome, once, and then open Chrome, every time you want to use it. Similarly, if you want to use the R package __pkg__ you need to first install __pkg__, once, and then load it every time you want to use it. 

That is always the case except for a few packages that R loads automatically for you every time you start a session. You can see what those packages are with `print(.packages())`. You will notice that the package __base__ is listed, so you can directly use its objects (functions and data) -- for example `sum()`. If these packages aren't enough you need to tell R that you want to use additional packages.

To tell R that you need objects from an additional package you can use two ways. Suppose you need the function `fun()` from the package __pkg__; these are your options: 
1. Tell R once by running `library(pkg)` and then use `fun()` directly.
2. Tell R every time you need `fun()` that it belongs to the package __pkg__ by using the sintax `pkg::fun()`.
The first approach saves space and effort; the second one expresses provenance more clearly and avoids conflict with objects named identically but from other packages. Thus the second approach is safest but the first one is often enough. Your best choice depends on the situation.

## When Are R Packages Updated

Alive software is dynamic and R packages are no exception. While users can access a stable -- released -- version of an R package, developers may continue to change a copy of it (branch) in preparation for the next release. There is no such a thing as a finished R package; the closest to that is a dead one.

Occationally you update an R package and realize that it changed in a way that you dislike. Are you stuck with the new version? Not at all. The packages __devtools__ and __remotes__ allow you to install older versions from CRAN, GitHub, and other repositories with [`install_version()`](https://goo.gl/Gbpz7g)` and also with [`install_<repository>()`](https://goo.gl/vGCLCV)` using the sintax `install_<repository>("user-or-organization/package@version")`, for example: `install_github("r-lib/httr@v0.4")`.


xxx cont. here. 

# How To Find, Install, And Use An R Package?
## Find An R Packages
* Point to blog about how to find R packages

## Install An R Package
* `install.packages()`
* __remotes__ and __devtools__
    * install_github()`
    * install_REPOSITORY()`

## Uninstall An R Package
* Always with `remove.packages()`, regardless of where you installed it from.

## Use An R Package


# Summary

xxx Compose a paragraph with the key content of each of the six w's.

# Resources

*  R packages book
* Jenny Bryan's slides
* RStudio community
* RStudio.cloud/primer
* RStudio webinars
* RStudio articles
